name: Bitcoin Core CI

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  bitcoin-core-ci:
    # TODO: Change ryanofsky to bitcoin-core when moving from fork to production.
    uses: ryanofsky/libmultiprocess/.github/workflows/bitcoin-core-ci.yml@support
    secrets: inherit
